apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: CLUSTER_NAME
  name: apiserver-CLUSTER_REGION
spec:
  machineType: t3.small
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: apiserver-CLUSTER_REGION
  role: APIServer
  subnets:
  - CLUSTER_REGION
